{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}
{% set name = data.get('name')|replace("tethysapp-", "")|lower %}

package:
  name: {{ name }}
  version: {{ data.get('version') }}

about:
  author: {{ data.get('author')}}
  description: {{ data.get('description')}}
  license: "{'name': 'release_package', 'version': '1.1.19', 'description': 'A tethys app that lets the user to visualize and query WSDL enpoints', 'long_description': '', 'author': 'Giovanni Romero Bustamante', 'author_email': 'gio.rombus@gmail.com', 'url': 'https://github.com/BYU-Hydroinformatics/Water-Data-Explorer', 'license': 'BSD 3-Clause License', 'tethys_version': '>=4.0.0', 'dev_url': 'https://github.com/BYU-Hydroinformatics/Water-Data-Explorer.git'}"
  dev_url: {{ data.get('dev_url') }}

outputs:
  - name: {{ name }}
extra:
  author_email: gio.rombus@gmail.com
  keywords: []
  recipe-maintainers:
  - TethysAppWarehouse

build:
  noarch: python
  preserve_egg_dir: true
  script: python setup.py install --record=record.txt
requirements:
  build:
  - python
  run:
  - geojson
  - pyproj
  - xmltodict
  - pyshp
  - geopandas
  - suds-community
  - pywaterml
  - numpy=1.21
source:
  path: ..
